name: 'SSH Connection Action with sshpass'
description: 'Connect to a remote server via SSH using sshpass and run commands'

inputs:
  user:
    description: 'User for SSH connection'
    required: true
    default: 'ubuntu'
  password:
    description: 'Password for SSH connection'
    required: true
  host:
    description: 'IP address or domain of the remote server'
    required: true
  port:
    description: 'SSH connection port'
    required: false
    default: '22'  # Default (standard SSH port)
  commands:
    description: 'Commands to run after SSH connection'
    required: true

runs:
  using: 'composite'
  steps:

    - name: Install SSHPASS
      id: install_sshpass
      shell: bash
      run: |
        sudo apt-get update && \
        sudo apt-get install -y sshpass

    - name: Give execution permissions to entrypoint.sh
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.sh

    - name: Run entrypoint.sh
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh "${{ inputs.password }}" "${{ inputs.user }}" "${{ inputs.host }}" "${{ inputs.port }}" "${{ inputs.commands }}"